
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkomm
 */
public class Mochi extends javax.swing.JFrame {

    /**
     * Creates new form Mochi
     */
    public Mochi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdVnl = new javax.swing.JRadioButton();
        rdClt = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtpsn = new javax.swing.JTextField();
        txtrasa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 0, 51));
        jLabel8.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("EPICUREAN MOCHI ICE CREAM");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(290, 0, 400, 90);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 870, 90);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setText("ISIAN DATA PEMBELI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 10, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 250, 60);

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setForeground(new java.awt.Color(51, 204, 255));
        jPanel3.setLayout(null);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit);
        btnEdit.setBounds(460, 20, 73, 23);

        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd);
        btnAdd.setBounds(100, 20, 73, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(190, 20, 73, 23);

        Reset.setText("Clear");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset);
        Reset.setBounds(280, 20, 73, 23);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh);
        btnRefresh.setBounds(370, 20, 73, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, 100, 610, 60);

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setForeground(new java.awt.Color(51, 204, 255));
        jPanel4.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Telp", "Rasa Mochi", "Rasa Ice Cream", "Jumlah Pesan", "Alamat"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 610, 90);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(260, 170, 610, 400);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(10, 200, 210, 30);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 130, 30);

        jLabel6.setText("Telp");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 130, 30);

        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelp);
        txtTelp.setBounds(10, 250, 210, 30);

        jLabel3.setText("Rasa Mochi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 280, 90, 20);

        buttonGroup1.add(rdVnl);
        rdVnl.setText("Vanilla");
        rdVnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVnlActionPerformed(evt);
            }
        });
        getContentPane().add(rdVnl);
        rdVnl.setBounds(10, 310, 100, 23);

        buttonGroup1.add(rdClt);
        rdClt.setText("Chocolate");
        rdClt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCltActionPerformed(evt);
            }
        });
        getContentPane().add(rdClt);
        rdClt.setBounds(120, 310, 100, 23);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane3.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 470, 220, 96);

        jPanel6.setBackground(new java.awt.Color(51, 204, 255));
        jPanel6.setForeground(new java.awt.Color(51, 204, 255));
        jPanel6.setLayout(null);

        jLabel5.setText("Alamat");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(10, 270, 130, 30);

        txtpsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpsnActionPerformed(evt);
            }
        });
        jPanel6.add(txtpsn);
        txtpsn.setBounds(10, 240, 210, 30);

        txtrasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrasaActionPerformed(evt);
            }
        });
        jPanel6.add(txtrasa);
        txtrasa.setBounds(10, 190, 210, 30);

        jLabel7.setText("Jumlah Pesan");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 220, 130, 30);

        jLabel4.setText("Rasa Ice Cream");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(10, 170, 130, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 170, 250, 400);

        setBounds(0, 0, 886, 609);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if ("".equals(txtNama.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtrasa.getText())
            || "".equals(txtTelp.getText()) || "".equals(txtpsn.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String RS = "";
            if (rdVnl.isSelected())
            {
                RS = "L";
            } else {
                RS = "P";
            }
            String SQL = "UPDATE t_siswa SET "
            + "WHERE Nama='"+txtNama.getText()+"',"+ "WHERE Kelas='"+txtTelp.getText()+"',"
            + "WHERE Telp='"+RS+"',"+ "WHERE Email='"+txtrasa.getText()+"'"
            + "WHERE Alamat='"+txtpsn.getText()+"'"
            + "WHERE NIS='"+txtAlamat.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 0)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if ("".equals(txtNama.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtrasa.getText())
            || "".equals(txtTelp.getText()) || "".equals(txtpsn.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String RS = "";
            if (rdVnl.isSelected())
            {
                RS = "Vanilla";
            } else {
                RS = "Chocolate";
            }
            String SQL = "INSERT INTO t_siswa (NIS, NamaSiswa, JenisKelamin, Kelas, Email, Alamat)"
            + "VALUES ('"+txtNama.getText()+"','"+txtTelp.getText()+"','"+RS+"',"
            + "'"+txtrasa.getText()+"','"+txtpsn.getText()+"','"+txtAlamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "GAgal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        txtTelp.setText("");
        txtNama.setText("");
        txtrasa.setText("");
        buttonGroup1.clearSelection();
        txtpsn.setText("");
        txtAlamat.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        selectData();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            txtNama.setText(tblData.getValueAt(baris, 0).toString());
            txtTelp.setText(tblData.getValueAt(baris,1).toString());
            if ("Vanilla".equals(tblData.getValueAt(baris, 2).toString())) {
                rdVnl.setSelected(true);
            }
            else {
                rdClt.setSelected(true);
            }
            txtrasa.setText(tblData.getValueAt(baris, 3).toString());
            txtpsn.setText(tblData.getValueAt(baris, 4).toString());
            txtAlamat.setText(tblData.getValueAt(baris, 5).toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseClicked

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void rdVnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVnlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdVnlActionPerformed

    private void rdCltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCltActionPerformed

    private void txtrasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrasaActionPerformed

    private void txtpsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpsnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mochi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdClt;
    private javax.swing.JRadioButton rdVnl;
    private javax.swing.JTable tblData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtpsn;
    private javax.swing.JTextField txtrasa;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
